const mongoose=require('mongoose');
const profileSchema=new mongoose.Schema({
    logo:{
        type:String,
        default:"default.jpg"
    },
    fullname:{
        firstname:{
            type:String,
            required:true
        },
        lastname:{
            type:String,
            required:true
        }
    },
    dateofbirth:{
        type:String,
        required:true
    },
    age:{
         type:Number,
        required:true
    },
    summary:{
        type:[String]
    },
    education:{
        type:[String],
        required:true
    },
    experience:{
        type:String,
        default:0
    },
    currentprofession:{
        type:String,
    },
    mobile:{
        type:String,
        required:true
    },
    skills:{
        type:[String]
    },
    address:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    userid:{
        type:String,
        required:true
    },
    resume:{
        type:String,
        required:true
    },
    updatedon:{
        type:Date,
        default:Date.now()
    }
})
module.exports=mongoose.model("usersProfile",profileSchema);